"""HATE API surface for import/export/authz/read model projections."""

from __future__ import annotations

from .authz import check_export_authz, check_import_authz, AuthorizationDecision
from .import_export import validate_bundle_import, export_safe_diagnostic
from .errors import (
    APIError,
    auth_unauthenticated,
    auth_unauthorized,
    auth_cross_tenant,
    req_invalid_filter,
    req_invalid_pagination,
    req_missing_required,
    req_invalid_sort,
    schema_unsupported,
    schema_incompatible,
    store_not_found,
    store_stale,
    store_rebuilding,
    store_corruption,
    export_failed,
    export_blocked,
    priv_quarantined,
    priv_redaction_failed,
    priv_restricted,
    priv_path_leak_prevented,
    error_list_to_dict,
)
from .read_model import (
    STALENESS_FRESH,
    STALENESS_STALE,
    STALENESS_REBUILDING,
    STALENESS_UNKNOWN,
    MIN_LIMIT,
    MAX_LIMIT,
    DEFAULT_LIMIT,
    PaginationInfo,
    StalenessInfo,
    SourceInfo,
    APIResponseEnvelope,
    build_read_model,
    validate_filters,
    validate_pagination,
    validate_sort,
    build_response,
    build_error_response,
    list_runs,
    get_run_detail,
    list_evidence,
    list_risks,
    list_artifacts,
    list_doctor_findings,
    RESOURCE_FILTERS,
    RESOURCE_SORT_FIELDS,
)

__all__ = [
    # authz
    "check_export_authz",
    "check_import_authz",
    "AuthorizationDecision",
    # import_export
    "validate_bundle_import",
    "export_safe_diagnostic",
    # errors
    "APIError",
    "auth_unauthenticated",
    "auth_unauthorized",
    "auth_cross_tenant",
    "req_invalid_filter",
    "req_invalid_pagination",
    "req_missing_required",
    "req_invalid_sort",
    "schema_unsupported",
    "schema_incompatible",
    "store_not_found",
    "store_stale",
    "store_rebuilding",
    "store_corruption",
    "export_failed",
    "export_blocked",
    "priv_quarantined",
    "priv_redaction_failed",
    "priv_restricted",
    "priv_path_leak_prevented",
    "error_list_to_dict",
    # read_model
    "STALENESS_FRESH",
    "STALENESS_STALE",
    "STALENESS_REBUILDING",
    "STALENESS_UNKNOWN",
    "MIN_LIMIT",
    "MAX_LIMIT",
    "DEFAULT_LIMIT",
    "PaginationInfo",
    "StalenessInfo",
    "SourceInfo",
    "APIResponseEnvelope",
    "build_read_model",
    "validate_filters",
    "validate_pagination",
    "validate_sort",
    "build_response",
    "build_error_response",
    "list_runs",
    "get_run_detail",
    "list_evidence",
    "list_risks",
    "list_artifacts",
    "list_doctor_findings",
    "RESOURCE_FILTERS",
    "RESOURCE_SORT_FIELDS",
]
